# Site settings
title: 、醉梦苍穹红颜断 
header-img: img/home-bg.jpg
email: 824963750@qq.com
description: "编码生涯的点点滴滴"
host: "127.0.0.1"
baseurl: ""
github_username:  lcy824963750

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","tmp","unless"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
